### ISSUE TITLE
Soulbind & /auc

### ISSUE THREAD

**Issue by larssieboy18** [mk7a/ItemSoulBind-Info#5]
**Plugin version**
0.6.2
**Spigot Version**
1.14.4 (Paper)

**To Reproduce**
Bind an item to a player, then let the player auction the item. The winning player will be able to use the item and select it, but he/she won't be able to retrieve it from a chest, pick it up after dropping or other things that would normally happen when an item is bound to another player.

**Expected behavior**
I don't know if it's possible, but make it so that SoulBound items are not able to be auctioned

**Screenshots**
N/A

**Additional context**
N/A

**Comment by mk7a** [comment]
Hi, can you make a gif showing the process of putting an item for auction? I have some ideas how to prevent it but I'd like to see exactly how it works with your auction plugin.

**Comment by larssieboy18** [comment]
Hi,

Here is a GIF showing the auction process: [GIFfrom Gyazo](https://gyazo.com/4ec1dcb53224db13de225d345839a96f/raw)]. I noticed later that the plugin does send a warning that someone else has a soulbound item and return it, however, I would like it to be disabled in auction completely to prevent scamming.

Best regards,
Lars

**Comment by mk7a** [comment]
Thank you for bringing this to my attention. Config option added in new version.
