### ISSUE TITLE
The Bows items dont bind on use

### ISSUE THREAD

**Issue by Jarlisteo** [mk7a/ItemSoulBind-Info#7]
**Plugin version**
last
**Spigot Version**
1.14
**To Reproduce**
Use a bow with bind on use

**Expected behavior**
the bow should bind on use

**Comment by mk7a** [comment]
Forgot about bows, thanks for reporting. Fixed in [0.8.0](https://www.spigotmc.org/resources/itemsoulbind.64541/update?update=301986)
